"""Market classifier rule tables — keyword maps used by market_classifier.

Ordering is significant: classification is first-match-wins, so more-specific
categories must appear BEFORE their generic parent. Keep this file free of
logic; accessors live in market_classifier.py.
"""

from __future__ import annotations

# Ordered list of (category, keywords).  First match wins, so more-specific
# categories (e.g. BTC_5m, BTC_ETF) must appear BEFORE their generic parent.
MARKET_CATEGORIES: dict[str, list[str]] = {
    "BTC_5m": ["bitcoin", "btc"],
    "BTC_ETF": ["bitcoin", "btc"],
    "BTC": ["bitcoin", "btc"],
    "ETH": ["ethereum", "eth"],
    "SOL": ["solana", "sol"],
    "Crypto_Alt": [
        "dogecoin",
        "doge",
        "shiba",
        "pepe",
        "xrp",
        "cardano",
        "ada",
        "polkadot",
        "dot",
        "avalanche",
        "avax",
        "matic",
        "polygon",
        "chainlink",
        "link",
        "uniswap",
        "uni",
        "defi",
        "crypto",
        "token",
        "altcoin",
        "meme coin",
    ],
    "Politics_US": [
        "president",
        "nominee",
        "trump",
        "biden",
        "election",
        "congress",
        "senate",
        "governor",
        "primary",
        "2024",
        "2025",
        "2026",
        "2028",
        "electoral",
        "swing state",
        "gop",
        "dnc",
        "republican",
        "democratic",
    ],
    "Politics_Global": [
        "prime minister",
        "election",
        "votes",
        "referendum",
        "parliament",
        "coalition",
        "presidential",
        "regime",
        "nato",
        "eu",
        "european union",
        "brexit",
        "france",
        "germany",
        "uk",
        "britain",
        "hungary",
        "poland",
        "turkey",
        "india",
        "japan",
        "brazil",
        "mexico",
        "canada",
        "australia",
    ],
    "Geopolitics": [
        "iran",
        "israel",
        "ukraine",
        "russia",
        "china",
        "war",
        "ceasefire",
        "sanction",
        "nato",
        "hormuz",
        "strait",
        "military",
        "invasion",
        "missile",
        "nuclear",
        "conflict",
        "taiwan",
        "gaza",
        "houthi",
        "hezbollah",
        "hamas",
    ],
    "Sports_Basketball": ["nba", "basketball", "ncaa"],
    "Sports_NFL": ["nfl", "football", "super bowl"],
    "Sports_Soccer": [
        "soccer",
        "premier league",
        "champions league",
        "la liga",
        "serie a",
        "bundesliga",
        "world cup",
    ],
    "Sports_Other": [
        "mlb",
        "nhl",
        "tennis",
        "cricket",
        "boxing",
        "ufc",
        "mma",
        "golf",
        "formula 1",
        "f1",
        "match",
        "championship",
        "playoff",
        "series",
        "race",
        "driver",
        "champion",
        "title",
        "round",
        "bout",
        "fight",
        "knockout",
    ],
    "Eurovision": ["eurovision", "song contest"],
    "Entertainment_Awards": [
        "oscar",
        "grammy",
        "emmy",
        "academy award",
        "mtv",
        "billboard",
        "golden globe",
        "tony",
    ],
    "Entertainment_Music": [
        "album",
        "song",
        "music",
        "concert",
        "tour",
        "spotify",
        "stream",
        "debut",
    ],
    "Entertainment_Film": [
        "movie",
        "film",
        "box office",
        "marvel",
        "dc",
        "disney",
        "netflix",
        "hbo",
        "streaming",
        "cinema",
    ],
    "Entertainment_Media": [
        "mrbeast",
        "elon musk",
        "celebrity",
        "influencer",
        "youtube",
        "tiktok",
        "twitch",
        "podcast",
    ],
    "Entertainment_Gaming": [
        "gta",
        "grand theft auto",
        "nintendo",
        "playstation",
        "xbox",
        "video game",
        "gaming",
        "esports",
        "steam",
        "nft",
        "metaverse",
    ],
    "Tech_Space": [
        "gemini",
        "spacex",
        "starship",
        "nasa",
        "space",
        "rocket",
        "launch",
        "satellite",
        "moon",
        "mars",
    ],
    "Tech_AI": [
        "ipo",
        "acquisition",
        "merger",
        "startup",
        "venture",
        "silicon valley",
        "google",
        "apple",
        "meta",
        "amazon",
        "microsoft",
        "nvidia",
        "tesla",
        "openai",
        "anthropic",
        "artificial intelligence",
        "robot",
        "automation",
        "chatgpt",
        "gpt",
        "llm",
        "model",
    ],
    "Regulation": [
        "bitcoin etf",
        "crypto regulation",
        "sec",
        "cftc",
        "cfpb",
        "fincen",
        "bill",
        "law",
        "court",
        "supreme court",
        "lawsuit",
        "regulation",
        "ban",
        "legal",
    ],
    "Finance": [
        "fed",
        "federal reserve",
        "interest rate",
        "rate cut",
        "rate hike",
        "inflation",
        "cpi",
        "gdp",
        "recession",
        "stock",
        "spx",
        "nasdaq",
        "dow",
        "s&p",
        "earnings",
        "microstrategy",
        "treasury",
        "yield",
        "bond",
    ],
    "Weather": [
        "temperature",
        "celsius",
        "fahrenheit",
        "weather",
        "hurricane",
        "tornado",
        "flood",
        "storm",
        "climate",
        "global warming",
        "heat",
        "snow",
        "rain",
    ],
    "Science_Health": [
        "covid",
        "vaccine",
        "pandemic",
        "virus",
        "drug",
        "fda",
        "medical",
        "health",
        "obesity",
        "longevity",
        "clinical",
        "trial",
        "cure",
        "treatment",
    ],
    "Science": [
        "nobel",
        "physics",
        "chemistry",
        "biology",
        "math",
        "discovery",
        "invention",
        "patent",
        "research",
    ],
}

# Short keywords that need word-boundary matching to avoid false positives.
# e.g. "eth" in "something", "sol" in "dissolve", "ai" in "said", "f1" in "f150"
_SHORT_KW = frozenset(
    {
        "eth",
        "sol",
        "ai",
        "sec",
        "fda",
        "gdp",
        "cpi",
        "fed",
        "dc",
        "eu",
        "uk",
        "f1",
        "nft",
        "ufc",
        "mma",
        "nhl",
        "nba",
        "nfl",
        "mlb",
        "uni",
        "dot",
        "ada",
        "xrp",
    }
)
