module.exports = {
  apps: [
    {
      name: 'polyedge-api',
      script: 'venv/bin/python',
      args: '-m uvicorn backend.api.main:app --host 0.0.0.0 --port 8100',
      cwd: '/home/openclaw/projects/1ai-poly-trader',
      env: {
        ADMIN_API_KEY: 'polyedge-admin-2026',
        LLM_DEFAULT_PROVIDER: 'openai',
        LLM_DEBATE_PROVIDER: 'openai',
        LLM_JUDGE_PROVIDER: 'openai',
        LLM_OPENAI_API_KEY: 'omniroute',
        LLM_OPENAI_BASE_URL: 'http://localhost:20128/v1',
        LLM_OPENAI_MODEL: 'auto/best-fast',
        MIROFISH_API_URL: 'http://localhost:5001',
        LIGHTER_ACCOUNT_INDEX: '0',
        LIGHTER_API_KEY_INDEX: '2',
        WALLET_FERNET_KEY: 'M7nIPAS8uCl34sjHjvfnpQAKi43Fkc56YW3cppgpnTs=',
        MAX_POSITION_FRACTION: '0.30',
        MAX_STRATEGY_DRAWDOWN_PCT: '0.50',
        MAX_CORRELATED_EXPOSURE_PCT: '0.80',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'polyedge-orchestrator',
      script: 'venv/bin/python',
      args: '-m backend.core.orchestrator',
      cwd: '/home/openclaw/projects/1ai-poly-trader',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
