module.exports = {
  apps: [
    {
      name: 'polyedge-api',
      script: 'venv/bin/python',
      args: '-m uvicorn backend.api.main:app --host 0.0.0.0 --port 8100',
      cwd: '/home/openclaw/projects/1ai-poly-trader',
      env: {
        ADMIN_API_KEY: '24c8bfd739504a528e1d24177c8e967a',
        LLM_DEFAULT_PROVIDER: 'groq',
        LLM_DEBATE_PROVIDER: 'groq',
        LLM_JUDGE_PROVIDER: 'groq',
        LLM_OPENAI_API_KEY: 'omniroute',
        LLM_OPENAI_BASE_URL: 'http://localhost:20128/v1',
        LLM_OPENAI_MODEL: 'auto/best-fast',
        MIROFISH_API_URL: 'http://localhost:5001',
        LIGHTER_ACCOUNT_INDEX: '0',
        LIGHTER_API_KEY_INDEX: '2',
        WALLET_FERNET_KEY: 'M7nIPAS8uCl34sjHjvfnpQAKi43Fkc56YW3cppgpnTs=',
        MAX_POSITION_FRACTION: '0.30',
        MAX_STRATEGY_DRAWDOWN_PCT: '0.50',
        MAX_CORRELATED_EXPOSURE_PCT: '0.80',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'polyedge-orchestrator',
      script: 'venv/bin/python',
      args: '-m backend.core.orchestrator',
      cwd: '/home/openclaw/projects/1ai-poly-trader',
      env: {
        TRADING_MODE: 'live',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'polyedge-frontend',
      script: '/home/openclaw/projects/1ai-poly-trader/frontend/node_modules/.bin/vite',
      args: '--host',
      cwd: '/home/openclaw/projects/1ai-poly-trader/frontend',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
    {
      name: 'mirofish-backend',
      script: '/home/openclaw/projects/mirofish/backend/venv/bin/python',
      args: '/home/openclaw/projects/mirofish/backend/run.py',
      cwd: '/home/openclaw/projects/mirofish/backend',
      env: {
        FLASK_PORT: '5001',
        FLASK_DEBUG: 'false',
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
    },
  ],
};
