"""Single source of truth for risk parameters.
Import from here instead of hardcoding in strategies, backtests, or risk managers.
"""

from backend.config import settings

# Position Sizing
DEFAULT_KELLY_FRACTION = settings.DEFAULT_KELLY_FRACTION
MAX_KELLY_FRACTION = settings.MAX_KELLY_FRACTION
DEFAULT_MAX_POSITION_USD = settings.POSITION_MAX_USD
DEFAULT_MAX_DAILY_LOSS_USD = settings.DEFAULT_MAX_DAILY_LOSS_USD

# Drawdown
DEFAULT_MAX_DRAWDOWN_PCT = settings.DEFAULT_MAX_DRAWDOWN_PCT
TERMINAL_DRAWDOWN_PCT = settings.TERMINAL_DRAWDOWN_PCT

# Bankroll
INITIAL_BANKROLL = settings.INITIAL_BANKROLL

# Circuit Breaker
CB_DEFAULT_FAILURE_THRESHOLD = settings.CB_FAILURE_THRESHOLD
CB_DEFAULT_RECOVERY_TIMEOUT = settings.CB_RECOVERY_TIMEOUT

# Learning
MAX_PARAM_CHANGE_FRACTION = settings.AUTO_IMPROVE_MAX_PARAM_CHANGE
ROLLBACK_DEGRADATION_THRESHOLD = settings.AUTO_IMPROVE_ROLLBACK_DEGRADATION
