"""add trading_wallets wallet_allocations copy_policies

Revision ID: 8f98f43940f4
Revises: 2c10e32ae3fa
Create Date: 2026-05-13 07:51:54.382353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8f98f43940f4'
down_revision: Union[str, Sequence[str], None] = '2c10e32ae3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copy_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('max_size_usd', sa.Float(), nullable=False),
    sa.Column('confidence_floor', sa.Float(), nullable=False),
    sa.Column('max_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('size_scale_factor', sa.Float(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_policies_id'), 'copy_policies', ['id'], unique=False)
    op.create_index(op.f('ix_copy_policies_source_name'), 'copy_policies', ['source_name'], unique=True)
    op.create_table('trading_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('encrypted_api_secret', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_wallets_address'), 'trading_wallets', ['address'], unique=True)
    op.create_index(op.f('ix_trading_wallets_id'), 'trading_wallets', ['id'], unique=False)
    op.create_index(op.f('ix_trading_wallets_label'), 'trading_wallets', ['label'], unique=True)
    op.create_table('wallet_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_exposure_usd', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_name'], ['strategy_config.strategy_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['trading_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_name', 'wallet_id', name='uq_strategy_wallet')
    )
    op.create_index(op.f('ix_wallet_allocations_id'), 'wallet_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_allocations_strategy_name'), 'wallet_allocations', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_wallet_allocations_wallet_id'), 'wallet_allocations', ['wallet_id'], unique=False)
    op.drop_index('ix_backtest_trades_id', table_name='backtest_trades')
    op.drop_index('ix_backtest_trades_run_id', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('ix_backtest_runs_id', table_name='backtest_runs')
    op.drop_index('ix_backtest_runs_strategy_name', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_column('bot_state', 'track_loss_limit_commodity')
    op.drop_column('bot_state', 'track_bankroll_commodity')
    op.drop_column('bot_state', 'track_pnl_realtime')
    op.drop_column('bot_state', 'track_pnl_whale')
    op.drop_column('bot_state', 'track_loss_limit_realtime')
    op.drop_column('bot_state', 'track_bankroll_whale')
    op.drop_column('bot_state', 'track_pnl_commodity')
    op.drop_column('bot_state', 'track_loss_limit_whale')
    op.drop_column('bot_state', 'track_bankroll_realtime')
    op.drop_index('ix_pending_approvals_status', table_name='pending_approvals')
    op.drop_index('ix_settlement_events_trade_id', table_name='settlement_events')
    op.drop_index('idx_trades_blockchain_verified', table_name='trades')
    op.drop_index('idx_trades_clob_order_id', table_name='trades')
    op.drop_index('idx_trades_last_sync_at', table_name='trades')
    op.drop_index('idx_trades_source', table_name='trades')
    op.drop_index('ix_trades_settled_mode', table_name='trades')
    op.drop_index('ix_trades_ticker_settled', table_name='trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_trades_ticker_settled', 'trades', ['market_ticker', 'settled'], unique=False)
    op.create_index('ix_trades_settled_mode', 'trades', ['settled', 'trading_mode'], unique=False)
    op.create_index('idx_trades_source', 'trades', ['source'], unique=False)
    op.create_index('idx_trades_last_sync_at', 'trades', ['last_sync_at'], unique=False)
    op.create_index('idx_trades_clob_order_id', 'trades', ['clob_order_id'], unique=False)
    op.create_index('idx_trades_blockchain_verified', 'trades', ['blockchain_verified'], unique=False)
    op.create_index('ix_settlement_events_trade_id', 'settlement_events', ['trade_id'], unique=False)
    op.create_index('ix_pending_approvals_status', 'pending_approvals', ['status'], unique=False)
    op.add_column('bot_state', sa.Column('track_bankroll_realtime', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_whale', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_commodity', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_whale', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_realtime', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_whale', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_pnl_realtime', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_bankroll_commodity', sa.FLOAT(), server_default=sa.text('(100.0)'), nullable=True))
    op.add_column('bot_state', sa.Column('track_loss_limit_commodity', sa.FLOAT(), server_default=sa.text('(50.0)'), nullable=True))
    op.create_table('backtest_runs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strategy_name', sa.VARCHAR(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('initial_bankroll', sa.FLOAT(), nullable=False),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('final_equity', sa.FLOAT(), nullable=False),
    sa.Column('total_pnl', sa.FLOAT(), nullable=False),
    sa.Column('total_return_pct', sa.FLOAT(), nullable=False),
    sa.Column('win_rate', sa.FLOAT(), nullable=False),
    sa.Column('total_trades', sa.INTEGER(), nullable=False),
    sa.Column('winning_trades', sa.INTEGER(), nullable=False),
    sa.Column('losing_trades', sa.INTEGER(), nullable=False),
    sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_runs_strategy_name', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index('ix_backtest_runs_id', 'backtest_runs', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('signal_id', sa.INTEGER(), nullable=True),
    sa.Column('market_ticker', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('direction', sa.VARCHAR(), nullable=False),
    sa.Column('entry_price', sa.FLOAT(), nullable=False),
    sa.Column('exit_price', sa.FLOAT(), nullable=True),
    sa.Column('size', sa.FLOAT(), nullable=False),
    sa.Column('pnl', sa.FLOAT(), nullable=False),
    sa.Column('result', sa.VARCHAR(), nullable=False),
    sa.Column('edge_at_entry', sa.FLOAT(), nullable=False),
    sa.Column('market_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('model_probability_at_entry', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('executed', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_trades_run_id', 'backtest_trades', ['run_id'], unique=False)
    op.create_index('ix_backtest_trades_id', 'backtest_trades', ['id'], unique=False)
    op.drop_index(op.f('ix_wallet_allocations_wallet_id'), table_name='wallet_allocations')
    op.drop_index(op.f('ix_wallet_allocations_strategy_name'), table_name='wallet_allocations')
    op.drop_index(op.f('ix_wallet_allocations_id'), table_name='wallet_allocations')
    op.drop_table('wallet_allocations')
    op.drop_index(op.f('ix_trading_wallets_label'), table_name='trading_wallets')
    op.drop_index(op.f('ix_trading_wallets_id'), table_name='trading_wallets')
    op.drop_index(op.f('ix_trading_wallets_address'), table_name='trading_wallets')
    op.drop_table('trading_wallets')
    op.drop_index(op.f('ix_copy_policies_source_name'), table_name='copy_policies')
    op.drop_index(op.f('ix_copy_policies_id'), table_name='copy_policies')
    op.drop_table('copy_policies')
    # ### end Alembic commands ###
