"""Carved verbatim out of ``backend/models/migration.py`` — statements moved, no logic changed."""

from . import migration as _facade

def _create_sentiment_cache_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "sentiment_cache"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS sentiment_cache (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        source VARCHAR(100),
                        symbol VARCHAR(20),
                        sentiment_score FLOAT,
                        confidence FLOAT,
                        details TEXT,
                        cached_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create sentiment_cache: {exc}"
            )
def _create_prediction_market_tables(db) -> None:
    conn = db.connection()
    for table_ddl in [
        """CREATE TABLE IF NOT EXISTS prediction_markets (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            platform VARCHAR(50),
            market_id VARCHAR(255) UNIQUE,
            question TEXT,
            description TEXT,
            outcome VARCHAR(50),
            probability FLOAT,
            volume FLOAT,
            liquidity FLOAT,
            close_time TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",
        """CREATE TABLE IF NOT EXISTS prediction_trades (
            id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            platform VARCHAR(50),
            market_id VARCHAR(255),
            trade_type VARCHAR(20),
            amount FLOAT,
            price FLOAT,
            outcome VARCHAR(50),
            pnl FLOAT,
            status VARCHAR(20),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",
    ]:
        try:
            conn.execute(_facade.text(table_ddl))
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create prediction_market table: {exc}"
            )
def _create_audit_log_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "audit_log"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS audit_log (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        action VARCHAR(255),
                        entity_type VARCHAR(100),
                        entity_id VARCHAR(100),
                        details TEXT,
                        user_id INTEGER,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create audit_log: {exc}"
            )
def _update_token_limit_supply(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "trading_settings"):
        _facade._add_column_if_missing(
            conn, "trading_settings", "token_limit_supply", "FLOAT"
        )
def _add_risk_profile_position_monitor(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "risk_profiles"):
        _facade._add_column_if_missing(
            conn, "risk_profiles", "max_positions", "INTEGER"
        )
def _create_trade_alerts_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "trade_alerts"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS trade_alerts (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        strategy_id INTEGER,
                        alert_type VARCHAR(100),
                        message TEXT,
                        severity VARCHAR(20),
                        is_read BOOLEAN DEFAULT FALSE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create trade_alerts: {exc}"
            )
def _add_strategy_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "strategies"):
        _facade._add_column_if_missing(conn, "strategies", "risk_score", "FLOAT")
        _facade._add_column_if_missing(conn, "strategies", "is_active", "BOOLEAN")
        _facade._add_column_if_missing(conn, "strategies", "config", "TEXT")
def _create_backup_state_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "backup_state"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS backup_state (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        backup_type VARCHAR(50),
                        state TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create backup_state: {exc}"
            )
def _create_scheduled_tasks_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "scheduled_tasks"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS scheduled_tasks (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        task_name VARCHAR(255),
                        task_type VARCHAR(100),
                        interval_seconds INTEGER,
                        last_run TIMESTAMP,
                        next_run TIMESTAMP,
                        is_active BOOLEAN DEFAULT TRUE,
                        config TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create scheduled_tasks: {exc}"
            )
def _add_strategy_generation_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "strategies"):
        _facade._add_column_if_missing(
            conn, "strategies", "generation", "INTEGER"
        )
        _facade._add_column_if_missing(
            conn, "strategies", "parent_strategy_id", "INTEGER"
        )
        _facade._add_column_if_missing(
            conn, "strategies", "evolution_score", "FLOAT"
        )
def _create_auto_withdrawal_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "auto_withdrawal"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS auto_withdrawal (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        exchange VARCHAR(50),
                        asset VARCHAR(20),
                        amount FLOAT,
                        withdrawal_address TEXT,
                        status VARCHAR(20),
                        tx_hash VARCHAR(255),
                        error_message TEXT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create auto_withdrawal: {exc}"
            )
def _add_withdrawal_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "withdrawals"):
        _facade._add_column_if_missing(
            conn, "withdrawals", "network_fee", "FLOAT"
        )
        _facade._add_column_if_missing(
            conn, "withdrawals", "confirmations", "INTEGER"
        )
        _facade._add_column_if_missing(
            conn, "withdrawals", "completed_at", _facade._TS_TYPE
        )
def _create_market_index_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "market_index"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS market_index (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        exchange VARCHAR(50),
                        symbol VARCHAR(20),
                        price FLOAT,
                        volume FLOAT,
                        change_24h FLOAT,
                        high_24h FLOAT,
                        low_24h FLOAT,
                        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create market_index: {exc}"
            )
def _add_missing_trade_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "trades"):
        _facade._add_column_if_missing(
            conn, "trades", "is_simulated", "BOOLEAN"
        )
        _facade._add_column_if_missing(
            conn, "trades", "take_profit_price", "FLOAT"
        )
        _facade._add_column_if_missing(
            conn, "trades", "stop_loss_price", "FLOAT"
        )
        _facade._add_column_if_missing(
            conn, "trades", "partial_fill", "BOOLEAN"
        )
        _facade._add_column_if_missing(
            conn, "trades", "fill_ratio", "FLOAT"
        )
        _facade._add_column_if_missing(
            conn, "trades", "risk_reward_ratio", "FLOAT"
        )
def _add_event_connection_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "event_connections"):
        _facade._add_column_if_missing(
            conn, "event_connections", "max_retries", "INTEGER"
        )
        _facade._add_column_if_missing(
            conn, "event_connections", "retry_delay", "FLOAT"
        )
def _add_health_check_columns(db) -> None:
    conn = db.connection()
    if _facade._table_exists(conn, "health_checks"):
        _facade._add_column_if_missing(
            conn, "health_checks", "subsystem", "VARCHAR(100)"
        )
        _facade._add_column_if_missing(
            conn, "health_checks", "duration_ms", "FLOAT"
        )
def _create_provider_settings_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "provider_settings"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS provider_settings (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        provider_name VARCHAR(100),
                        setting_key VARCHAR(100),
                        setting_value TEXT,
                        is_encrypted BOOLEAN DEFAULT FALSE,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        UNIQUE(provider_name, setting_key)
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create provider_settings: {exc}"
            )
def _create_cex_exchange_orders_table(db) -> None:
    conn = db.connection()
    if not _facade._table_exists(conn, "cex_exchange_orders"):
        try:
            conn.execute(
                _facade.text(
                    """CREATE TABLE IF NOT EXISTS cex_exchange_orders (
                        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        exchange VARCHAR(50),
                        order_id VARCHAR(255),
                        symbol VARCHAR(20),
                        side VARCHAR(10),
                        order_type VARCHAR(50),
                        quantity FLOAT,
                        price FLOAT,
                        status VARCHAR(50),
                        filled_quantity FLOAT,
                        remaining_quantity FLOAT,
                        cost FLOAT,
                        fees TEXT,
                        raw_response TEXT,
                        strategy_id INTEGER,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )"""
                )
            )
            conn.connection.commit()
        except Exception as exc:
            _facade.logger.warning(
                f"Could not create cex_exchange_orders: {exc}"
            )
def ensure_schema() -> None:
    """Migrate the database schema to the latest version.

    Creates missing tables, adds missing columns, and runs data fixups.
    May be called on every startup — designed to be idempotent.
    """
    t0 = _facade.time.time()

    db = _facade.SessionLocal()
    try:
        conn = db.connection()
        _facade._add_column_if_missing(
            conn, "system_settings", "telegram_channel_status", "VARCHAR(255)"
        )
        _facade._add_column_if_missing(
            conn,
            "system_settings",
            "telegram_notify_errors",
            "BOOLEAN",
        )
        _facade._add_column_if_missing(
            conn, "risk_profiles", "max_concurrent_trades", "FLOAT"
        )
        _facade._add_column_if_missing(
            conn, "strategy_performance", "target_asset", "VARCHAR(50)"
        )

        _facade._create_strategy_orders_table(db)
        _facade._create_knowledge_graph_indexes(db)
        _facade._create_system_health_table(db)
        _facade._create_market_metrics_table(db)
        _facade._create_strategy_analysis_table(db)
        _facade._create_execution_metrics_table(db)
        _facade._create_error_log_table(db)
        _facade._create_knowledge_graph_tables(db)
        _facade._create_trade_insights_table(db)
        _facade._create_position_monitor_table(db)
        _create_sentiment_cache_table(db)
        _create_prediction_market_tables(db)
        _create_audit_log_table(db)
        _update_token_limit_supply(db)
        _add_risk_profile_position_monitor(db)
        _create_trade_alerts_table(db)
        _add_strategy_columns(db)
        _create_backup_state_table(db)
        _create_scheduled_tasks_table(db)
        _add_strategy_generation_columns(db)
        _create_auto_withdrawal_table(db)
        _add_withdrawal_columns(db)
        _create_market_index_table(db)
        _add_missing_trade_columns(db)
        _add_event_connection_columns(db)
        _add_health_check_columns(db)
        _create_provider_settings_table(db)
        _create_cex_exchange_orders_table(db)

        _facade.logger.info(
            f"ensure_schema completed in {_facade.time.time() - t0:.2f}s — "
            f"all migrations applied"
        )
    except Exception as exc:
        _facade.logger.error(f"ensure_schema migration failed: {exc}")
        raise
    finally:
        db.close()
def init_db(repair_if_needed: bool = True) -> None:
    """Initialise the database schema: create all tables, run migrations, seed defaults.

    If the database is corrupted and *repair_if_needed* is ``True``, attempt
    data recovery, wipe the file, recreate, and restore recovered rows.
    Safe to call repeatedly.
    """
    try:
        _facade.Base.metadata.create_all(bind=_facade.engine, checkfirst=True)
        ensure_schema()
        _facade.seed_default_data()
    except Exception as e:
        if "database disk image is malformed" in str(e) and repair_if_needed:
            _facade.logger.warning(f"Database corrupted, attempting repair: {e}")
            _facade._publish_corruption_alert("database_corruption_detected", str(e))

            db_path = _facade.app_settings.DATABASE_URL.replace(
                "sqlite:///", ""
            ).replace("./", "")
            recovered = _facade._attempt_data_recovery(db_path)
            recovered_table_count = len(recovered)
            recovered_row_count = sum(
                len(rows) for rows in recovered.values()
            )
            _facade.logger.info(
                f"Recovered data from {recovered_table_count} table(s), "
                f"{recovered_row_count} total rows before wiping"
            )

            try:
                _facade.engine.dispose()

                if _facade.os.path.exists(db_path):
                    _facade.os.unlink(db_path)
                    _facade.logger.info(f"Removed corrupted database: {db_path}")

                _facade.Base.metadata.create_all(bind=_facade.engine, checkfirst=True)
                ensure_schema()
                _facade.seed_default_data()

                if recovered:
                    _facade._restore_recovered_data(recovered)

                _facade._publish_corruption_alert(
                    "database_repair_succeeded",
                    "Database repaired after corruption",
                    {
                        "tables_recovered": recovered_table_count,
                        "rows_recovered": recovered_row_count,
                    },
                )
                _facade.logger.info("Database repaired successfully")
            except Exception as repair_error:
                _facade._publish_corruption_alert(
                    "database_repair_failed", str(repair_error)
                )
                _facade.logger.error(f"Database repair failed: {repair_error}")
                raise
        else:
            raise
