"""Domain model: signal — split from database.py.
Keeps backward compatibility via database.py re-exports.
"""
import json
from datetime import datetime, timezone
from typing import Optional
from loguru import logger

from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    DateTime,
    Boolean,
    JSON,
    Text,
)

from backend.models.base_db import Base

class Signal(Base):
    """Trading signals generated by the bot."""

    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, index=True)
    market_ticker = Column(String, index=True)
    platform = Column(String)
    market_type = Column(String, default="btc", index=True)  # "btc" or "weather"
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)

    direction = Column(String)
    model_probability = Column(Float)
    market_price = Column(Float)
    edge = Column(Float)
    confidence = Column(Float)

    kelly_fraction = Column(Float)
    suggested_size = Column(Float)

    sources = Column(JSON)
    reasoning = Column(String)

    # Edge discovery tracking
    track_name = Column(
        String, nullable=True, default="legacy", index=True
    )  # Which edge track generated this signal
    execution_mode = Column(String, nullable=True, default="paper")  # 'paper' or 'live'
    token_id = Column(String, nullable=True)

    executed = Column(Boolean, default=False)

    # Calibration tracking — filled after settlement
    actual_outcome = Column(
        String, nullable=True
    )  # "up" or "down" — actual market result
    outcome_correct = Column(
        Boolean, nullable=True
    )  # did our direction prediction match?
    settlement_value = Column(Float, nullable=True)  # 1.0=UP won, 0.0=DOWN won
    settled_at = Column(DateTime, nullable=True)  # when we recorded the outcome



class AILog(Base):
    """Log of all AI API calls."""

    __tablename__ = "ai_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)
    provider = Column(String, index=True)
    model = Column(String)

    prompt = Column(String)
    response = Column(String)
    call_type = Column(String, index=True)

    latency_ms = Column(Float)
    tokens_used = Column(Integer)
    cost_usd = Column(Float)

    related_market = Column(String, nullable=True)
    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)



class EMOSCalibrationState(Base):
    __tablename__ = "emos_calibration_state"
    city = Column(String, primary_key=True)
    obs_pairs_json = Column(Text, nullable=False)
    a = Column(Float, nullable=False)
    b = Column(Float, nullable=False)
    last_updated = Column(DateTime, nullable=True)



class ScanLog(Base):
    """Log of each market scan run."""

    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True, index=True)
    run_id = Column(String, unique=True, index=True)
    started_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    completed_at = Column(DateTime, nullable=True)

    categories_scanned = Column(JSON)
    platforms_scanned = Column(JSON)

    markets_found = Column(Integer, default=0)
    signals_generated = Column(Integer, default=0)
    trades_executed = Column(Integer, default=0)

    ai_calls_made = Column(Integer, default=0)
    ai_cost_usd = Column(Float, default=0.0)

    success = Column(Boolean, default=True)
    error = Column(String, nullable=True)



class DecisionLog(Base):
    __tablename__ = "decision_log"
    id = Column(Integer, primary_key=True, index=True)
    strategy = Column(String, nullable=False, index=True)
    market_ticker = Column(String, nullable=False, index=True)
    decision = Column(String, nullable=False)  # BUY, SKIP, SELL, HOLD, ERROR
    confidence = Column(Float, nullable=True)
    signal_data = Column(Text, nullable=True)  # JSON string
    reason = Column(Text, nullable=True)
    outcome = Column(String, nullable=True)  # WIN, LOSS, PUSH — filled at settlement
    # NULL = pending pickup by executor; EXECUTED, SKIPPED, FAILED once handled
    execution_status = Column(String, nullable=True, index=True)
    created_at = Column(
        DateTime, default=lambda: datetime.now(timezone.utc), index=True
    )

